repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0  # Use the latest version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: local
    hooks:
      - id: clang-format
        name: clang-format
        entry: clang-format -i
        language: system
        files: \.(c|cpp|h|hpp)$
